### ISSUE TITLE
Field 'servicesDescription' is required for type with serial name 'dev.ja.marketplace.client.PluginVendor', but it was missing at path: $.vendor

### ISSUE THREAD

**Issue by jonathanlermitage** [jansorg/marketplace-stats-kotlin#1]
Hi,  
I tested this app with one of my plugins (https://plugins.jetbrains.com/plugin/11058-extra-icons). I generated a token using this page https://plugins.jetbrains.com/author/me/tokens.  
I checked out the project and updated `config-template.json` with my plugin id (11058) and my generated token.  
Ran `./gradlew clean build -x test`: OK. Ran `java -jar ./build/libs/marketplace-client-all.jar /(absolute path of my)/config-template.json`. I faced this error:  
```
[jon@jon marketplace-stats-kotlin]$ java -jar ./build/libs/marketplace-client-all.jar /home/jon/prj/marketplace-stats-kotlin/config-template.json 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" io.ktor.serialization.JsonConvertException: Illegal input: Field 'servicesDescription' is required for type with serial name 'dev.ja.marketplace.client.PluginVendor', but it was missing at path: $.vendor
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:116)
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:243)
        at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source)
        at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:230)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:262)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invokeSuspend(Logging.kt:201)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Logging.kt)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Logging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:88)
        at dev.ja.marketplace.client.KtorMarketplaceClient.pluginInfo(KtorMarketplaceClient.kt:112)
        at dev.ja.marketplace.client.KtorMarketplaceClient$pluginInfo$1.invokeSuspend(KtorMarketplaceClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at dev.ja.marketplace.Application.main(Application.kt:26)
Caused by: kotlinx.serialization.MissingFieldException: Field 'servicesDescription' is required for type with serial name 'dev.ja.marketplace.client.PluginVendor', but it was missing at path: $.vendor
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:93)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
        at dev.ja.marketplace.client.PluginInfo$$serializer.deserialize(types.kt:35)
        at dev.ja.marketplace.client.PluginInfo$$serializer.deserialize(types.kt:35)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
        ... 42 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'servicesDescription' is required for type with serial name 'dev.ja.marketplace.client.PluginVendor', but it was missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at dev.ja.marketplace.client.PluginVendor.<init>(types.kt:99)
        at dev.ja.marketplace.client.PluginVendor$$serializer.deserialize(types.kt:99)
        at dev.ja.marketplace.client.PluginVendor$$serializer.deserialize(types.kt:99)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        ... 49 more

```
Maybe something is missing in my plugin description? I attached a screenshot of my plugin description page, if it can help.
![Screenshot 2023-08-07 at 15-56-20 Extra Icons - IntelliJ IDEs Plugin Marketplace](https://github.com/jansorg/marketplace-stats-kotlin/assets/857535/bf64780a-464b-40a4-9141-042c7536b8d6)

```
[jon@jon marketplace-stats-kotlin]$ ./gradlew --version

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.4 (BellSoft 17.0.4+8-LTS)
OS:           Linux 6.4.8-arch1-1 amd64
```

**Comment by jansorg** [comment]
Thanks for reporting! Could you pull the latest update and try again, please?
The marketplace API is undocumented, so there are a few misaligned properties.

**Comment by jonathanlermitage** [comment]
Thx!  
Sure, now I see 
```
kotlinx.serialization.MissingFieldException: Field 'videoUrl' is required for type with serial name 'dev.ja.marketplace.client.PluginUrls', but it was missing at path: $.urls
```
I will set it as optional, and do the same thing if I found more issues like this.

**Comment by jansorg** [comment]
I've pushed a commit to make url properties optional. Let me know if there are more errors like this.

**Comment by jonathanlermitage** [comment]
I faced 
```
kotlinx.serialization.MissingFieldException: Fields [docText, copyright] are required for type with serial name 'dev.ja.marketplace.client.PluginInfo', but they were missing at path: $
```
After making them optional, it works fine. I can visit http://localhost:8080/ and my data seems good. Thx!

**Comment by jansorg** [comment]
I pushed a commit to make them optional. Please reopen when you notice more properties like this.

**Comment by jonathanlermitage** [comment]
Hi! Just updated to the latest version, and this time the email field should be optional:  
```
MissingFieldException: Field 'email' is required for type with serial name 'dev.ja.marketplace.client.PluginVendor', but it was missing at path: $.vendor
```
