### ISSUE TITLE
Support CNY currency

### ISSUE THREAD

**Issue by AntonShuvaev** [jansorg/marketplace-stats-kotlin#13]
I've noticed the following exception in logs:
`kotlinx.serialization.SerializationException: dev.ja.marketplace.client.Currency does not contain element with name 'CNY' at path $[68].currency`

**Comment by jonathanlermitage** [comment]
Same here, when displaying info for a paid plugin. No problem with free plugins. Here is the console output and the stacktrace: 
```
C:\Projects>java -jar marketplace-stats-all.jar marketplace-stats-kotlin-config.json
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Launching web server: http://127.0.0.1:8080/
Exception in thread "DefaultDispatcher-worker-1" io.ktor.serialization.JsonConvertException: Illegal input: dev.ja.marketplace.client.Currency does not contain element with name 'CNY' at path $[822].currency
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:116)
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:243)
        at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source)
        at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:230)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:262)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invokeSuspend(Logging.kt:201)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Logging.kt)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Logging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:88)
        at dev.ja.marketplace.client.KtorMarketplaceClient.getSalesInfo(KtorMarketplaceClient.kt:275)
        at dev.ja.marketplace.client.KtorMarketplaceClient.access$getSalesInfo(KtorMarketplaceClient.kt:23)
        at dev.ja.marketplace.client.KtorMarketplaceClient$getSalesInfo$1.invokeSuspend(KtorMarketplaceClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3b263eee, Dispatchers.IO]
Caused by: kotlinx.serialization.SerializationException: dev.ja.marketplace.client.Currency does not contain element with name 'CNY' at path $[822].currency
        at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(JsonNamesMap.kt:107)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(StreamingJsonDecoder.kt:358)
        at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:139)
        at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:105)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
        at dev.ja.marketplace.client.PluginSale$$serializer.deserialize(types.kt:282)
        at dev.ja.marketplace.client.PluginSale$$serializer.deserialize(types.kt:282)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
        ... 42 more
17:40:50.863 [eventLoopGroupProxy-4-1] ERROR ktor.application - Unhandled: GET - /
io.ktor.serialization.JsonConvertException: Illegal input: dev.ja.marketplace.client.Currency does not contain element with name 'CNY' at path $[822].currency
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90) ~[marketplace-stats-all.jar:?]
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224) ~[marketplace-stats-all.jar:?]
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:116) ~[marketplace-stats-all.jar:?]
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113) ~[marketplace-stats-all.jar:?]
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:243) ~[marketplace-stats-all.jar:?]
        at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source) ~[marketplace-stats-all.jar:?]
        at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:230) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:262) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invokeSuspend(Logging.kt:201) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Logging.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Logging.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98) ~[marketplace-stats-all.jar:?]
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77) ~[marketplace-stats-all.jar:?]
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:88) ~[marketplace-stats-all.jar:?]
        at dev.ja.marketplace.client.KtorMarketplaceClient.getSalesInfo(KtorMarketplaceClient.kt:275) ~[marketplace-stats-all.jar:?]
        at dev.ja.marketplace.client.KtorMarketplaceClient.access$getSalesInfo(KtorMarketplaceClient.kt:23) ~[marketplace-stats-all.jar:?]
        at dev.ja.marketplace.client.KtorMarketplaceClient$getSalesInfo$1.invokeSuspend(KtorMarketplaceClient.kt) ~[marketplace-stats-all.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[marketplace-stats-all.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[marketplace-stats-all.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[marketplace-stats-all.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[marketplace-stats-all.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[marketplace-stats-all.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[marketplace-stats-all.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[marketplace-stats-all.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[marketplace-stats-all.jar:?]
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296) ~[marketplace-stats-all.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [marketplace-stats-all.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: kotlinx.serialization.SerializationException: dev.ja.marketplace.client.Currency does not contain element with name 'CNY' at path $[822].currency
        at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(JsonNamesMap.kt:107) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(StreamingJsonDecoder.kt:358) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:139) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:105) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165) ~[marketplace-stats-all.jar:?]
        at dev.ja.marketplace.client.PluginSale$$serializer.deserialize(types.kt:282) ~[marketplace-stats-all.jar:?]
        at dev.ja.marketplace.client.PluginSale$$serializer.deserialize(types.kt:282) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[marketplace-stats-all.jar:?]
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107) ~[marketplace-stats-all.jar:?]
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82) ~[marketplace-stats-all.jar:?]
        ... 45 more
```

**Comment by jansorg** [comment]
Fixed by https://github.com/jansorg/marketplace-stats-kotlin/commit/41eb9015d38d8a14bef4e06d593a2b88372c71bc
Release 0.1.1 is now available with the fix.

The Marketplace added a new Currency for customer payment (Chinese YEN), which was undefined in the client. A better fix would be generic support for any currency, but I've postponed that fix for now.
